name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project SITIENS.xcodeproj

      - name: Build and Test
        run: |
          xcodebuild clean build test \
          -project SITIENS.xcodeproj \
          -scheme "SITIENS" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
          ONLY_ACTIVE_ARCH=YES
