name: iOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build et tests via l’action xcodebuild
      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
        with:
          project: SITIENS.xcodeproj       # le projet Xcode
          scheme: SITIENS.SITIENS          # le schéma à builder
          destination: 'platform=iOS Simulator,name=iPhone 16e,OS=18.4'
          action: test                     # on exécute les tests
          result-bundle-path: 'TestResults/TestResults.xcresult'

      # 3️⃣ Traiter les résultats des tests
      - name: Process Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: ${{ success() || failure() }}
        with:
          path: TestResults/TestResults.xcresult
